replicaCount: 1

type: persistent | readonly

image:
  repository: dbb-set-docker-stage-dev-local.bahnhub.tech.rz.db.de
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  create: true

securityContext:
  capabilities:
    drop:
      - KILL
      - MKNOD
      - SETGID
      - SETUID
  runAsUser: 1001000000

loadbalancer:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"

# Default resources
resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: "1"
    memory: 1Gi
