# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: CC0-1.0
name: Push docker images to GitHub container registry

on:
  push:
    branches: [main, staging, actions]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main, staging]

jobs:
  deploy-frontend-image:
    runs-on: ubuntu-latest
    name: Build and push frontend image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/dsd-dbs/capella-collab-manager/frontend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Fetch version
        run: |
          node frontend/fetch-version.ts
      - name: Prepare environment.prod.ts
        run: |
          cp frontend/src/environments/environment.ts frontend/src/environments/environment.prod.ts
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          tags: ${{ steps.meta.outputs.tags }}
          push: true
