# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: CC0-1.0
name: mocks

on:
  push:
    branches: ['**']
    tags: ["v*.*.*"]
  pull_request:
    branches: [master, staging]

jobs:
  deploy-docker-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - image: ghcr.io/dsd-dbs/capella-collab-manager/t4c/server/mock
            context: mocks/t4c-server
          - image: ghcr.io/dsd-dbs/capella-collab-manager/t4c/licence/mock
            context: mocks/licence-server
    name: build and push ${{ matrix.context }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
