# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: CC0-1.0
name: push

on:
  push:
    branches: ['**']
    tags: ["v*.*.*"]
  pull_request:
    branches: [master, staging]

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Build and push backend image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch version
        run: |
          python backend/generate_git_archival.py
      - uses: ./.github/workflows/docker-template.yml
        with:
          context: ./backend
          image: ghcr.io/dsd-dbs/capella-collab-manager/backend
  frontend:
    runs-on: ubuntu-latest
    name: Build and push frontend image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Fetch version
        run: |
          node frontend/fetch-version.ts
      - name: Prepare environment.prod.ts
        run: |
          cp frontend/src/environments/environment.ts frontend/src/environments/environment.prod.ts
      - uses: ./.github/workflows/docker-template.yml
        with:
          context: ./frontend
          image: ghcr.io/dsd-dbs/capella-collab-manager/frontend
  docs-and-mocks:
    runs-on: ubuntu-latest
    name: Build and push ${{ matrix.name }} image
    strategy:
      matrix:
        include:
          - name: t4c-server-mock
            image: ghcr.io/dsd-dbs/capella-collab-manager/t4c/server/mock
            context: mocks/t4c-server
          - name: t4c-license-mock
            image: ghcr.io/dsd-dbs/capella-collab-manager/t4c/licence/mock
            context: mocks/licence-server
          - name: docs
            image: ghcr.io/dsd-dbs/capella-collab-manager/docs
            context: ./docs/user
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: ./.github/workflows/docker-template.yml
        with:
          context: ${{ matrix.context }}
          image: ${{ matrix.image }}
  install-chart:
    runs-on: ubuntu-latest
    needs: [backend, frontend, docs-and-mocks]
    name: Install chart in kind cluster
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install helm
        uses: azure/setup-helm@v3
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/not/used # Only required to export the tag, image name is not used
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Resolve base image
        # Extract tag from docker metadata
        id: tag
        run: |
          export IMAGE=${{ steps.meta.outputs.tags }}
          echo "::set-output name=tag::${IMAGE##*:}"
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      - name: Create sessions namespace
        run: |
          kubectl create namespace t4c-sessions
      - name: Add registry token
        run: |
          kubectl create secret docker-registry github \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }}
      - name: Add secret to default serviceaccount
        run: |
          kubectl patch serviceaccount default \
            -p '{"imagePullSecrets": [{"name": "github"}]}'
      - name: Install chart
        run: |
          export TAG=${{ steps.tag.outputs.tag }}

          helm install test \
          --set docker.registry.internal="ghcr.io/dsd-dbs/capella-collab-manager" \
          --set docker.images.frontend="/frontend:$TAG" \
          --set docker.images.backend="/backend:$TAG" \
          --set docker.images.docs="/docs:$TAG" \
          --set t4cServer.apis.usageStats="http://test-licence-server-mock:80/mock" \
          --set t4cServer.apis.restAPI="http://test-t4c-server-mock:80/mock/api/v1.0" \
          ./helm
      - name: Wait for all containers to be ready
        run: |
          kubectl wait --all --for=condition=Ready pods --timeout=5m
      - name: Print status of Pods
        if: always()
        run: |
          kubectl get pods
      - name: Describe deployments
        if: always()
        run: |
          kubectl describe deployment
      - name: Describe pods
        if: always()
        run: |
          kubectl describe pods
      - name: Print logs of backend container
        if: always()
        run: |
          kubectl logs deployment/test-backend
